# parto/brush/presets/builtin.py
"""
Parto Brush System — Built-in Presets
Immutable factory for Parto standard factory brush presets.
Author & Maintainer: Ali Kamrani (علی کامرانی)
"""

from typing import List
from ..models.preset import BrushPreset


def get_builtin_presets() -> List[BrushPreset]:
    """
    Returns the authoritative list of factory built-in brush presets.
    Each preset is marked is_builtin=True to guard against deletion.
    """
    return [
        # --- Basic ---
        BrushPreset(
            name="Basic Round",
            size=12,
            opacity=1.0,
            flow=1.0,
            hardness=0.8,
            spacing=0.25,
            is_eraser=False,
            is_builtin=True,
            category="Basic",
            description="Standard general-purpose round brush",
            dynamics_size="pressure",
            dynamics_opacity="off",
        ),
        BrushPreset(
            name="Soft Round",
            size=24,
            opacity=0.8,
            flow=0.8,
            hardness=0.15,
            spacing=0.20,
            is_eraser=False,
            is_builtin=True,
            category="Basic",
            description="Soft feathered edges for blending",
            dynamics_size="pressure",
            dynamics_opacity="pressure",
        ),
        BrushPreset(
            name="Hard Round",
            size=16,
            opacity=1.0,
            flow=1.0,
            hardness=1.0,
            spacing=0.20,
            is_eraser=False,
            is_builtin=True,
            category="Basic",
            description="Crisp, sharp solid round brush",
            dynamics_size="off",
            dynamics_opacity="off",
        ),
        # --- Pencil ---
        BrushPreset(
            name="Pencil",
            size=2,
            opacity=0.95,
            flow=1.0,
            hardness=0.95,
            spacing=0.15,
            is_eraser=False,
            is_builtin=True,
            category="Pencil",
            description="Fine line sketching tool",
            dynamics_size="pressure",
            dynamics_opacity="pressure",
        ),
        BrushPreset(
            name="Rough Sketch",
            size=4,
            opacity=0.85,
            flow=0.9,
            hardness=0.75,
            spacing=0.20,
            is_eraser=False,
            is_builtin=True,
            category="Pencil",
            description="Textured graphite sketch pencil",
            dynamics_size="pressure",
            dynamics_opacity="velocity",
            scatter=0.08,
        ),
        # --- Ink ---
        BrushPreset(
            name="Ink",
            size=6,
            opacity=1.0,
            flow=1.0,
            hardness=0.9,
            spacing=0.10,
            is_eraser=False,
            is_builtin=True,
            category="Ink",
            description="Fluid continuous inking line",
            smoothing=0.35,
            dynamics_size="pressure",
        ),
        BrushPreset(
            name="Calligraphy",
            size=14,
            opacity=1.0,
            flow=1.0,
            hardness=0.95,
            spacing=0.10,
            is_eraser=False,
            is_builtin=True,
            category="Ink",
            angle=45.0,
            roundness=0.25,
            smoothing=0.4,
            description="Chiseled flat pen for lettering and flourishing",
            dynamics_size="pressure",
            dynamics_angle="tilt",
        ),
        # --- Paint ---
        BrushPreset(
            name="Oil Round",
            size=28,
            opacity=0.9,
            flow=0.85,
            hardness=0.7,
            spacing=0.15,
            is_eraser=False,
            is_builtin=True,
            category="Paint",
            roundness=0.8,
            angle=15.0,
            description="Heavy, opaque painterly stroke",
            dynamics_size="pressure",
            dynamics_flow="pressure",
        ),
        BrushPreset(
            name="Watercolor Wash",
            size=48,
            opacity=0.45,
            flow=0.5,
            hardness=0.25,
            spacing=0.18,
            is_eraser=False,
            is_builtin=True,
            category="Paint",
            description="Dilute translucent watercolor wash",
            blend_mode="multiply",
            dynamics_opacity="pressure",
        ),
        # --- Airbrush ---
        BrushPreset(
            name="Airbrush",
            size=40,
            opacity=0.35,
            flow=0.45,
            hardness=0.02,
            spacing=0.15,
            is_eraser=False,
            is_builtin=True,
            category="Airbrush",
            description="Diffuse soft aerosol spray",
            dynamics_flow="pressure",
            dynamics_size="pressure",
        ),
        BrushPreset(
            name="Soft Spray",
            size=60,
            opacity=0.25,
            flow=0.3,
            hardness=0.01,
            spacing=0.20,
            is_eraser=False,
            is_builtin=True,
            category="Airbrush",
            description="Broad atmospheric feathering airbrush",
            dynamics_flow="pressure",
        ),
        # --- Marker ---
        BrushPreset(
            name="Marker",
            size=22,
            opacity=0.55,
            flow=0.75,
            hardness=0.7,
            spacing=0.18,
            is_eraser=False,
            is_builtin=True,
            category="Marker",
            roundness=0.5,
            angle=30.0,
            description="Semi-transparent layering marker",
            blend_mode="multiply",
            dynamics_size="pressure",
        ),
        BrushPreset(
            name="Chisel Marker",
            size=30,
            opacity=0.6,
            flow=0.8,
            hardness=0.9,
            spacing=0.12,
            is_eraser=False,
            is_builtin=True,
            category="Marker",
            roundness=0.2,
            angle=60.0,
            description="Wide angled chisel tip highlighter",
        ),
        # --- Texture ---
        BrushPreset(
            name="Charcoal Texture",
            size=18,
            opacity=0.85,
            flow=0.8,
            hardness=0.6,
            spacing=0.22,
            is_eraser=False,
            is_builtin=True,
            category="Texture",
            scatter=0.25,
            size_jitter=0.2,
            description="Grainy charcoal with natural tooth",
            dynamics_size="pressure",
            dynamics_opacity="pressure",
        ),
        BrushPreset(
            name="Stipple Texture",
            size=24,
            opacity=0.75,
            flow=0.7,
            hardness=0.85,
            spacing=0.45,
            is_eraser=False,
            is_builtin=True,
            category="Texture",
            scatter=0.4,
            size_jitter=0.35,
            description="Dot stippling and organic particulate texture",
            dynamics_size="random",
        ),
        # --- Eraser ---
        BrushPreset(
            name="Eraser",
            size=20,
            opacity=1.0,
            flow=1.0,
            hardness=0.85,
            spacing=0.20,
            is_eraser=True,
            is_builtin=True,
            category="Eraser",
            description="Erases pixels from the active layer",
            dynamics_size="pressure",
        ),
        BrushPreset(
            name="Soft Eraser",
            size=32,
            opacity=0.65,
            flow=0.7,
            hardness=0.2,
            spacing=0.20,
            is_eraser=True,
            is_builtin=True,
            category="Eraser",
            description="Feathered eraser for gradual fade-outs",
            dynamics_opacity="pressure",
        ),
    ]
